#!/bin/sh

if git-rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --name-status --cached $against -- | cut -c3-` ; do
  # Check for describe.only(), describe.skip(), it.only(), it.skip()
  if egrep -q '(describe|it)\.(only|skip)' "$FILE"
  then
    echo 'ERROR:' $FILE 'can not have skip() or only() tests'
    exit 1
  fi

  # Check for console.log()
  if grep -q 'console.log' "$FILE" && [ "$FILE" != 'server.litcoffee' ]
  then
    echo 'ERROR:' $FILE 'can not use console.log()'
    exit 1
  fi

done
exit

